In [34]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.

def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines



In [38]:
import pandas as pd 

traning_dst = pd.read_csv("02_data.csv", header=0, index_col=None)

X = np.array(traning_dst.iloc[:,:2])
y = np.array(traning_dst.iloc[:,2])

trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25)


[(array([0.55152414]), array([-2.13117352])),
 (array([3.75673789]), array([-3.59593078])),
 (array([55.12356555]), array([-27.42299077])),
 (array([-66.92361128]), array([30.27413562])),
 (array([-27.98727507]), array([12.7461482])),
 (array([-19.2926987]), array([9.15303058])),
 (array([-13.64472063]), array([6.51809159])),
 (array([-12.14652179]), array([6.04906022])),
 (array([-10.64754883]), array([5.34407081])),
 (array([-9.46150222]), array([4.78625534])),
 (array([-9.11638068]), array([4.8096319])),
 (array([-8.37738427]), array([4.45849432])),
 (array([-7.56145983]), array([3.92361156])),
 (array([-7.1540751]), array([3.74292553])),
 (array([-6.78255947]), array([3.5781484])),
 (array([-6.44237543]), array([3.42726768])),
 (array([-6.12971985]), array([3.28859656])),
 (array([-5.84138118]), array([3.16071064])),
 (array([-5.57462872]), array([3.04239879])),
 (array([-5.32712588]), array([2.93262466])),
 (array([-5.09686157]), array([2.83049628])),
 (array([-4.88209541]), array